config/routes.rb
Rails.application.routes.draw do

  resources :chapters do
    resources :songs, shallow: true, except: [:show, :index]
    put 'move', on: :member
  end

  root 'chapters#index'
  devise_for :users
  get 'profile', to: 'home#profile'
  put 'profile', to: 'home#update_profile'

  mount API => '/'
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  include DeleteMarkable
  scope :ordered, -> { order(:position) }
  has_many :songs, inverse_of: :chapter, dependent: :destroy
  validates_presence_of :name
  acts_as_list

  def move_to(destination)
    case destination
      when 'top' then self.move_to_top
      when 'up' then self.move_higher
      when 'down' then self.move_lower
      when 'bottom' then self.move_to_bottom
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :move, :destroy]

  def index
    @chapters = Chapter.ordered
    respond_to do |format|
      format.html
      format.js { render 'shared/index' }
    end
  end

  def show
    @songs = @chapter.songs
  end

  def new
    @chapter = Chapter.new
    respond_to do |format|
      format.html { render 'form' }
    end
  end

  def edit
    respond_to do |format|
      format.html { render 'form' }
    end
  end

  def create
    @chapter = Chapter.new(chapter_params)
    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: t('chapters.created') }
      else
        format.html { render 'form' }
      end
    end
  end

  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: t('chapters.updated') }
      else
        format.html { render 'form' }
      end
    end
  end

  def move
    @chapter.move_to params[:destination]
    @chapters = Chapter.ordered
    render 'shared/index'
  end

  def destroy
    # @chapter.destroy
    @chapter.mark_deleted
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: t('chapters.deleted') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:name, :position)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= Chapter.human_attribute_name :name
      %th= Chapter.human_attribute_name :position
      %th
  %tbody
  - @chapters.each do |chapter|
    %tr
      %td= link_to chapter.name, chapter_path(chapter)
      %td
        .btn-group.btn-group-xs
          = link_to glyph(:arrow_up), move_chapter_path(chapter, destination: :top), method: :put, remote: true, class: 'btn btn-default', title: t('helpers.links.move_to_top')
          = link_to glyph(:chevron_up), move_chapter_path(chapter, destination: :up), method: :put, remote: true, class: 'btn btn-default', title: t('helpers.links.move_to_up')
          %span.label.label-primary.btn= chapter.position
          = link_to glyph(:chevron_down), move_chapter_path(chapter, destination: :down), method: :put, remote: true, class: 'btn btn-default', title: t('helpers.links.move_to_down')
          = link_to glyph(:arrow_down), move_chapter_path(chapter, destination: :bottom), method: :put, remote: true, class: 'btn btn-default', title: t('helpers.links.move_to_bottom')
      %td.actions
        .btn-group.btn-group-xs
          = link_to glyph(:edit), edit_chapter_path(chapter), class: 'btn btn-default', title: t('helpers.links.edit')
          = link_to glyph(:trash), chapter, method: :delete, data: { confirm: t('chapters.delete_confirmation') }, class: 'btn btn-danger', title: t('helpers.links.delete')

app/views/chapters/form.html.haml
= auto_header_tag @chapter
= simple_form_for @chapter do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :position
  .form-actions
    = link_to t('helpers.links.back'), :back, class: 'btn btn-default btn-lg'
    = link_to t('helpers.links.show'), @chapter, class: 'btn btn-default btn-lg' if @chapter.persisted?
    = submit_button f

app/views/chapters/index.html.haml
%h1
  = t '.title'
  = link_to t('.new'), new_chapter_path, class: 'btn btn-success'
#resource_table= render 'table'

app/views/chapters/show.html.haml
.page-header
  %h1= @chapter.name
  = link_to t('helpers.links.back'), chapters_path, class: 'btn btn-default'
  = link_to t('helpers.links.edit'), edit_chapter_path(@chapter), class: 'btn btn-default'
  = link_to t('helpers.links.delete'), @chapter, method: :delete, data: { confirm: t('chapters.delete_confirmation') }, class: 'btn btn-danger'

%h2
  = t 'songs.index.title'
  = link_to t('songs.new.title'), new_chapter_song_path(@chapter), class: 'btn btn-success'
%table.table.table-hover
  %tbody
    - @songs.each do |song|
      %tr
        %td= link_to song.name, edit_song_path(song)
        %td.actions= link_to glyph(:trash), song, method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-danger btn-xs', title: t('helpers.links.delete')