config/routes.rb
Rails.application.routes.draw do

  resources :chapters do
    resources :songs, shallow: true, except: [:show, :index]
    put 'move', on: :member
  end

  root 'chapters#index'
  devise_for :users
  get 'profile', to: 'home#profile'
  put 'profile', to: 'home#update_profile'

  mount API => '/'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to glyph(:home)+t('application_name'), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  = menu_item glyph(:user)+t('profile'), profile_path
  = menu_divider
  = menu_item glyph(:log_out)+t('devise.sessions.sign_out'), destroy_user_session_path, method: 'delete'
- else
  = menu_divider
  = menu_item glyph(:log_in)+t('devise.sessions.sign_in'), new_user_session_path
  -#= menu_item 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html{lang: 'ru'}
  %head
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title= content_for?(:title) ? yield(:title) : 'Song Book'
    %meta{name: 'description', content: "#{content_for?(:description) ? yield(:description) : t('application_name')}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{role: 'main'}
      = render 'layouts/messages'
      .container= yield